import React, { useEffect } from 'react'; 
import styles from '../styles/About.module.css'
import Image from 'next/image'
import Head from 'next/head'


const About = (props) => {
    
    // useEffect(()=>{

    // })

    return(
        <>
        <Head>
            <title>Next About page</title>
            <meta name="About" content="Generated by create next app" />
        </Head>
        <div className='bg-info'> 
            <h2 className={styles.about_test}>This is about file</h2> 
            {/* <img src='/about-001.jpeg' /> */}
            <Image src="/about-001.jpeg" width={400} height={200} alt='test'></Image>
        </div>
        </>
    )
}

export default About